apps/api/src/app/app.e2e.spec.ts, apps/api/src/app/runs/runs.controller.ts, apps/api/src/app/runs/runs.service.ts, apps/api/src/app/runs/schemas/run.schema.ts, apps/frontend/src/app/runs/runs.component.ts, libs/client/src/lib/client-example.ts, libs/client/src/lib/client.ts, libs/common/src/index.ts, libs/common/src/lib/api-url.ts, libs/common/src/lib/runs/dto/set-leader-request.dto.ts, libs/common/src/lib/runs/dto/set-leader-response.dto.ts, libs/common/src/lib/runs/run.ts
=> feat(api,client): add leader functionality

apps/api/src/app/app.e2e.spec.ts, apps/api/src/app/runs/runs.controller.ts, apps/api/src/app/runs/runs.service.ts, apps/api/src/app/runs/schemas/run.schema.ts, libs/common/src/lib/api-url.ts
=> feat(api): add ability to abort run

apps/api/src/app/app.e2e.spec.ts, apps/api/src/app/runs/runs.controller.ts, apps/api/src/app/runs/runs.service.ts, apps/api/src/app/runs/schemas/run.schema.ts, apps/api/src/app/tasks/tasks.service.ts, libs/client/src/lib/client.ts, libs/common/src/lib/api-url.ts, libs/common/src/lib/runs/run-status.ts
=> feat(api): add ability to fail run

apps/api/Dockerfile, apps/frontend/Dockerfile, apps/frontend/nginx/default.conf.template, docker-compose.build.yml, docker-compose.yml, nx.json, scripts/docker.sh
=> build: dockerize

apps/api/src/app/app.e2e.spec.ts, apps/api/src/app/runs/runs.controller.ts, apps/api/src/app/runs/runs.service.ts, libs/common/src/lib/api-url.ts
=> feat(api): add /api/runs/{id} route

apps/api/src/app/app.e2e.spec.ts, apps/api/src/app/runs/runs.service.ts, apps/api/src/app/runs/schemas/run.schema.ts, apps/api/src/app/tasks/tasks.service.ts, libs/common/src/lib/runs/dto/create-run-request.dto.ts, libs/common/src/lib/runs/run.ts
=> feat(api): add runners field

apps/api/src/app/runs/runs.service.ts, apps/api/src/app/runs/schemas/run.schema.ts, apps/api/src/app/tasks/schemas/task.schema.ts, apps/api/src/app/tasks/tasks.service.ts, apps/frontend/src/app/runs/runs.component.ts, apps/frontend/src/app/runs/tasks/tasks.component.ts, libs/client/src/lib/client-example.ts, libs/common/src/lib/runs/dto/create-run-request.dto.ts, libs/common/src/lib/runs/run.ts, libs/common/src/lib/tasks/dto/create-tasks.dto.ts, libs/common/src/lib/tasks/task-priority.ts, libs/common/src/lib/tasks/task.ts
=> feat: run prioritization

apps/api/src/app/runs/schemas/run.schema.ts, apps/api/src/app/tasks/tasks.service.ts, apps/frontend/src/app/runs/runs.component.ts, libs/common/src/lib/runs/dto/create-run-request.dto.ts, libs/common/src/lib/runs/run.ts
=> feat(api): add run runner affinity option

apps/api/src/app/app.e2e.spec.ts, apps/api/src/app/runs/runs.service.ts, apps/api/src/app/runs/schemas/run.schema.ts, apps/api/src/app/tasks/tasks.service.ts, libs/common/src/lib/runs/run-status.ts, libs/common/src/lib/runs/run.ts
=> refactor(api): replace CLOSED status by run property

apps/api/src/app/app.e2e.spec.ts, apps/api/src/app/runs/runs.service.ts, apps/api/src/app/runs/schemas/run.schema.ts, apps/api/src/app/tasks/schemas/task.schema.ts, apps/api/src/app/tasks/tasks.service.ts, libs/common/src/lib/runs/dto/create-run-request.dto.ts
=> feat(api): add run failFast

apps/frontend/src/app/runs/run-details/run-details-tasks.component.html, apps/frontend/src/app/runs/run-details/run-details-tasks.component.scss, apps/frontend/src/app/runs/run-details/run-details-tasks.component.ts, apps/frontend/src/app/runs/runs.component.ts, apps/frontend/src/app/runs/runs.module.ts
build(frontend): add a quick filter for the tasks page. Shuffle columns. Open tasks with one click
=> build(frontend): add a quick filter for the tasks page. Shuffle columns

.husky/commit-msg, .husky/pre-commit, commitlint.config.js, package-lock.json, package.json
add pre-commit hook and run formatter and linter in it
=> ci(monorepo): add pre-commit hook and run formatter and linter in it

apps/api/src/app.e2e.spec.ts, apps/api/src/runs/run.entity.ts, apps/api/src/runs/runs.service.ts
=> fix(api): automatically complete run when no tasks

apps/frontend-e2e/src/fixtures/execution/details.json, apps/frontend-e2e/src/fixtures/execution/tasks.json, apps/frontend-e2e/src/integration/execution.spec.ts, apps/frontend/src/app/runs/run-details/run-details-execution.component.ts
=> fix(frontend): identify duplicated commands in execution view

apps/frontend/src/app/runs/run-details/run-details-execution.component.ts, package-lock.json, package.json
=> feat(frontend): change execution color scheme

apps/api/src/app.e2e.spec.ts, apps/api/src/runs/run.entity.ts, apps/api/src/runs/runs.service.ts, apps/api/src/tasks/task.entity.ts, apps/api/src/tasks/tasks.service.ts, libs/common/src/lib/tasks/task-status.ts
=> feat(api): automatically abort running tasks when failFast enabled

apps/frontend/src/app/runs/run-details/run-details-details.component.ts
=> fix(frontend): issue with undefined date

libs/client/project.json, libs/client/tsconfig.lib.json, libs/common/project.json, libs/common/tsconfig.lib.json
=> build(client): fix project deps

apps/api/Dockerfile, apps/frontend/Dockerfile, libs/db/Dockerfile, nx.json
=> ci(monorepo): docker images could not been built #111

.gitignore, .idx/dev.nix, .idx/on-start.sh, .idx/policy.json, .idx/registries.conf, .idx/settings.json
=> Add idx.dev workspace support #113

apps/frontend/src/app/runs/run-details/run-details-task-log.component.ts, apps/frontend/src/app/runs/run-details/run-details-tasks.component.ts, libs/client/src/lib/client-example.ts
=> White text is invisible on Task log file preview #115

apps/api/src/app.e2e.spec.ts, apps/api/src/tasks/pending-tasks.service.ts, apps/api/src/tasks/task.entity.ts, apps/api/src/tasks/tasks.service.ts, apps/frontend/src/app/runs/run-details/run-details-tasks.component.ts, libs/client/src/lib/client-example.ts, libs/client/src/lib/client.ts, libs/common/src/lib/tasks/dto/create-tasks.dto.ts, libs/db/src/migrations/1717111649620-tskmgr.js
=> feat(tskmgr): add Dependency first task scheduler support #94

libs/client/package.json, libs/client/src/lib/client.ts, package-lock.json, package.json
=> refactor: remove node-fetch

libs/client/src/lib/client.ts
=> feat(client): add parallelId to environment variables #127

README.md, apps/api/Dockerfile, apps/api/dev.Dockerfile, apps/frontend/Dockerfile, libs/db/Dockerfile, libs/db/dev.Dockerfile
=> chore: upgrade docker node 22 lts
